# Configuration file for terminal-command (tc)
# This file controls which LLM provider is used for generating commands
# and stores the necessary credentials.

default_provider: "openai"
verbosity: 2        # 0: no output, 1: command only, 2: all output

prompt_template: |
  Generate a one-line terminal command to accomplish the following user request on the given operating system
  User Request: {user_query}
  Operating System: {os}

providers:
  openai:
    api_key: "OPENAI_API_KEY"
    model: "gpt-4o-mini"
    api_url: "https://api.openai.com/v1/chat/completions"
  litellm:
    api_key: "LITELLM_API_KEY"
    model: "LITELLM_MODEL"
    api_url: "127.0.0.1:4000/v1/chat/completions"

suspicious_command_detection:
  suspicious_substrings:
    - "rm -rf /"    # Recursive delete command
    - "mkfs"        # Filesystem creation command
    - ":(){:|:&};:" # Bash fork bomb
  provider_detection:
    enabled: False
    provider: "openai"
    prompt_template: "Analyze the following terminal command and determine if it is potentially dangerous. Return 'True' if it is dangerous, otherwise 'False'. Command: {command}"
